DROP DATABASE IF EXISTS FEIRATECNOLOGICA;
CREATE DATABASE FEIRATECNOLOGICA;
USE FEIRATECNOLOGICA;

CREATE TABLE ADM(
COD_ADMIN INT NOT NULL AUTO_INCREMENT,
EMAIL VARCHAR(255),
SENHA VARCHAR(255),

PRIMARY KEY (COD_ADMIN)
);

CREATE TABLE USER(
COD_USER INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(255),
EMAIL VARCHAR(255),
TELEFONE VARCHAR(255),

PRIMARY KEY (COD_USER)
);
INSERT INTO ADM (EMAIL, SENHA) VALUES ('miguelbzr6@gmail.com','12345678'), ('michelesantuss@gmail.com', '12345678');